In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [2]:
customer = pd.read_csv("/content/drive/MyDrive/Optimizing Airline Loyalty & Retention Dataset (Summer Projects '26)/Customer Loyalty History.csv")
flight = pd.read_csv("/content/drive/MyDrive/Optimizing Airline Loyalty & Retention Dataset (Summer Projects '26)/Customer Flight Activity.csv")
calendar = pd.read_csv("/content/drive/MyDrive/Optimizing Airline Loyalty & Retention Dataset (Summer Projects '26)/Calendar.csv")

print(customer.shape)
print(flight.shape)
print(calendar.shape)

(16737, 16)
(392936, 8)
(2557, 4)

In [3]:
print("="*50)
print("CUSTOMER DATA")
print("="*50)

display(customer.head())
display(customer.info())

print("\n")

print("="*50)
print("FLIGHT DATA")
print("="*50)

display(flight.head())
display(flight.info())

==================================================
CUSTOMER DATA
==================================================

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,7,2018.0,1.0
3,608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,NaN,Single,Star,3839.75,Standard,2013,2,NaN,NaN
4,530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.0,Married,Star,3842.79,Standard,2014,10,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16737 entries, 0 to 16736
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Loyalty Number      16737 non-null  int64
 1   Country             16737 non-null  object
 2   Province            16737 non-null  object
 3   City                16737 non-null  object
 4   Postal Code         16737 non-null  object
 5   Gender              16737 non-null  object
 6   Education           16737 non-null  object
 7   Salary              12499 non-null  float64
 8   Marital Status      16737 non-null  object
 9   Loyalty Card        16737 non-null  object
 10  CLV                 16737 non-null  float64
 11  Enrollment Type     16737 non-null  object
 12  Enrollment Year     16737 non-null  int64
 13  Enrollment Month    16737 non-null  int64
 14  Cancellation Year   2067 non-null   float64
 15  Cancellation Month  2067 non-null   float64
dtypes: float64(4), int64(3), object(9)
memory usage: 2.0+ MB

None

==================================================
FLIGHT DATA
==================================================

,Loyalty Number,Year,Month,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
0,100590,2018,6,12,15276,22914.0,0,0
1,100590,2018,7,12,9168,13752.0,0,0
2,100590,2018,5,4,6504,9756.0,0,0
3,100590,2018,10,0,0,0.0,512,92
4,100590,2018,2,0,0,0.0,0,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 392936 entries, 0 to 392935
Data columns (total 8 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Loyalty Number               392936 non-null  int64
 1   Year                         392936 non-null  int64
 2   Month                        392936 non-null  int64
 3   Total Flights                392936 non-null  int64
 4   Distance                     392936 non-null  int64
 5   Points Accumulated           392936 non-null  float64
 6   Points Redeemed              392936 non-null  int64
 7   Dollar Cost Points Redeemed  392936 non-null  int64
dtypes: float64(1), int64(7)
memory usage: 24.0 MB

None

In [4]:
missing_customer = (
    customer.isnull()
    .sum()
    .sort_values(ascending=False)
    .to_frame("Missing_Count")
)

missing_customer["Missing_%"] = (
    missing_customer["Missing_Count"]
    / len(customer)
    * 100
)

missing_customer

                    Missing_Count  Missing_%
Cancellation Month          14670  87.650117
Cancellation Year           14670  87.650117
Salary                       4238  25.321145
Loyalty Number                  0   0.000000
City                            0   0.000000
Postal Code                     0   0.000000
Province                        0   0.000000
Country                         0   0.000000
Education                       0   0.000000
Gender                          0   0.000000
Marital Status                  0   0.000000
Loyalty Card                    0   0.000000
Enrollment Type                 0   0.000000
CLV                             0   0.000000
Enrollment Month                0   0.000000
Enrollment Year                 0   0.000000

In [5]:
negative_salary = customer[customer["Salary"] < 0]

print("Negative salary records:", len(negative_salary))

negative_salary[
    ["Loyalty Number","Salary"]
].head()

Negative salary records: 20

      Loyalty Number   Salary
1082          542976 -49830.0
1894          959977 -12497.0
2471          232755 -46683.0
3575          525245 -45962.0
3932          603070 -19325.0

In [6]:
customer.loc[
    customer["Salary"] < 0,
    "Salary"
] = np.nan

In [7]:
flight["Date"] = pd.to_datetime(
    flight["Year"].astype(str)
    + "-"
    + flight["Month"].astype(str)
    + "-01"
)

In [8]:
duplicate_rows = flight.duplicated(
    subset=["Loyalty Number", "Date"],
    keep=False
)

duplicates = flight[duplicate_rows]

print("Duplicate records:")
print(len(duplicates))

duplicates.sort_values(
    ["Loyalty Number", "Date"]
).head(20)

Duplicate records:
7718

,Loyalty Number,Year,Month,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed,Date
177037,101902,2017,1,0,0,0.0,0,0,2017-01-01
177038,101902,2017,1,0,0,0.0,0,0,2017-01-01
187056,101902,2017,2,0,0,0.0,0,0,2017-02-01
187057,101902,2017,2,0,0,0.0,0,0,2017-02-01
196869,101902,2017,3,0,0,0.0,0,0,2017-03-01
196870,101902,2017,3,0,0,0.0,0,0,2017-03-01
137472,101902,2017,4,1,667,667.0,0,0,2017-04-01
149793,101902,2017,4,1,2499,2499.0,488,88,2017-04-01
55777,101902,2017,5,3,7263,7263.0,0,0,2017-05-01
97849,101902,2017,5,2,3762,3762.0,0,0,2017-05-01
57365,101902,2017,6,3,4971,4971.0,0,0,2017-06-01
57366,101902,2017,6,3,5763,5763.0,0,0,2017-06-01
234037,101902,2017,7,0,0,0.0,0,0,2017-07-01
234038,101902,2017,7,0,0,0.0,0,0,2017-07-01
11348,101902,2017,8,5,3825,3825.0,0,0,2017-08-01
28437,101902,2017,8,4,8952,8952.0,0,0,2017-08-01
103177,101902,2017,9,2,3734,3734.0,0,0,2017-09-01
144439,101902,2017,9,1,2187,2187.0,0,0,2017-09-01
104888,101902,2017,10,2,1274,1274.0,0,0,2017-10-01
146126,101902,2017,10,1,1466,1466.0,0,0,2017-10-01

In [9]:
flight_clean = (
    flight
    .groupby(
        ["Loyalty Number", "Date"],
        as_index=False
    )
    .agg({
        "Year":"first",
        "Month":"first",
        "Total Flights":"sum",
        "Distance":"sum",
        "Points Accumulated":"sum",
        "Points Redeemed":"sum",
        "Dollar Cost Points Redeemed":"sum"
    })
)

print(flight_clean.shape)

(389065, 9)

In [10]:
dup_check = flight_clean.duplicated(
    subset=["Loyalty Number", "Date"]
).sum()

print("Remaining duplicates:", dup_check)

Remaining duplicates: 0

In [11]:
month_counts = (
    flight_clean
    .groupby("Loyalty Number")
    ["Date"]
    .nunique()
)

In [12]:
month_counts.describe()

count    16737.000000
mean        23.245803
std          3.039129
min         11.000000
25%         24.000000
50%         24.000000
75%         24.000000
max         24.000000
Name: Date, dtype: float64

In [13]:
month_counts.value_counts().sort_index()

Date
11      971
24    15766
Name: count, dtype: int64

In [14]:
customer.to_csv(
    "customer_clean.csv",
    index=False
)

flight_clean.to_csv(
    "flight_clean.csv",
    index=False
)

In [15]:
customers_11_months = month_counts[
    month_counts == 11
].index

customer[
    customer["Loyalty Number"].isin(customers_11_months)
][
    [
        "Loyalty Number",
        "Cancellation Year",
        "Cancellation Month"
    ]
].head(20)

     Loyalty Number  Cancellation Year  Cancellation Month
18           172755                NaN                 NaN
36           938981                NaN                 NaN
65           386082             2018.0                11.0
69           112522                NaN                 NaN
73           330694                NaN                 NaN
96           472521                NaN                 NaN
113          967300             2018.0                11.0
118          920716                NaN                 NaN
132          366540                NaN                 NaN
149          766335                NaN                 NaN
177          645919                NaN                 NaN
184          675879                NaN                 NaN
187          827194                NaN                 NaN
201          110262                NaN                 NaN
209          342980                NaN                 NaN
234          342483                NaN                 NaN
239          384146             2018.0                12.0
309          977693                NaN                 NaN
312          443967                NaN                 NaN
319          556492                NaN                 NaN

In [16]:
customer[
    customer["Loyalty Number"].isin(customers_11_months)
]["Cancellation Year"].notna().mean()

np.float64(0.1184346035015448)

In [17]:
flight_clean["YearMonth"] = (
    flight_clean["Date"]
    .dt.to_period("M")
)

flight_clean.head()

,Loyalty Number,Date,Year,Month,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed,YearMonth
0,100018,2017-01-01,2017,1,1,601,601.0,0,0,2017-01
1,100018,2017-02-01,2017,2,0,0,0.0,0,0,2017-02
2,100018,2017-03-01,2017,3,4,9648,9648.0,438,79,2017-03
3,100018,2017-04-01,2017,4,1,1654,1654.0,0,0,2017-04
4,100018,2017-05-01,2017,5,0,0,0.0,0,0,2017-05

In [18]:
master = flight_clean.merge(
    customer,
    on="Loyalty Number",
    how="left"
)

print(master.shape)
master.head()

(389065, 25)

,Loyalty Number,Date,Year,Month,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed,YearMonth,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,100018,2017-01-01,2017,1,1,601,601.0,0,0,2017-01,Canada,Alberta,Edmonton,T9G 1W3,Female,Bachelor,92552.0,Married,Aurora,7919.2,Standard,2016,8,NaN,NaN
1,100018,2017-02-01,2017,2,0,0,0.0,0,0,2017-02,Canada,Alberta,Edmonton,T9G 1W3,Female,Bachelor,92552.0,Married,Aurora,7919.2,Standard,2016,8,NaN,NaN
2,100018,2017-03-01,2017,3,4,9648,9648.0,438,79,2017-03,Canada,Alberta,Edmonton,T9G 1W3,Female,Bachelor,92552.0,Married,Aurora,7919.2,Standard,2016,8,NaN,NaN
3,100018,2017-04-01,2017,4,1,1654,1654.0,0,0,2017-04,Canada,Alberta,Edmonton,T9G 1W3,Female,Bachelor,92552.0,Married,Aurora,7919.2,Standard,2016,8,NaN,NaN
4,100018,2017-05-01,2017,5,0,0,0.0,0,0,2017-05,Canada,Alberta,Edmonton,T9G 1W3,Female,Bachelor,92552.0,Married,Aurora,7919.2,Standard,2016,8,NaN,NaN

In [19]:
master.isnull().sum().sort_values(
    ascending=False
).head(15)

Cancellation Month             340952
Cancellation Year              340952
Salary                          98838
Date                                0
Total Flights                       0
Distance                            0
Year                                0
Month                               0
Loyalty Number                      0
Dollar Cost Points Redeemed         0
Points Redeemed                     0
Points Accumulated                  0
YearMonth                           0
City                                0
Postal Code                         0
dtype: int64

In [20]:
master["Active_Month"] = np.where(
    master["Total Flights"] > 0,
    1,
    0
)

In [21]:
master["Active_Month"].value_counts(normalize=True)

Active_Month
0    0.542562
1    0.457438
Name: proportion, dtype: float64

In [22]:
master = master.sort_values(
    ["Loyalty Number", "Date"]
).reset_index(drop=True)

In [23]:
master.to_csv(
    "master_panel.csv",
    index=False
)

print(master.shape)

(389065, 26)

In [24]:
master = master.sort_values(
    ["Loyalty Number", "Date"]
).reset_index(drop=True)

In [25]:
master["Engaged"] = np.where(
    (
        (master["Total Flights"] > 0)
        |
        (master["Points Accumulated"] > 0)
    ),
    1,
    0
)

In [26]:
def create_churn_labels(df):

    df = df.sort_values(
        ["Loyalty Number", "Date"]
    ).copy()

    churn_labels = []

    for customer_id, group in df.groupby("Loyalty Number"):

        engagement = group["Engaged"].values

        labels = []

        for i in range(len(group)):

            future_window = engagement[i+1:i+7]

            if len(future_window) < 6:
                labels.append(np.nan)

            elif future_window.sum() == 0:
                labels.append(1)

            else:
                labels.append(0)

        churn_labels.extend(labels)

    df["Churn"] = churn_labels

    return df

In [27]:
master = create_churn_labels(master)

In [28]:
master["Churn"].value_counts(
    normalize=True,
    dropna=False
)

Churn
0.0    0.584581
NaN    0.258111
1.0    0.157308
Name: proportion, dtype: float64

In [29]:
model_data = master[
    master["Churn"].notna()
].copy()

In [30]:
print(model_data.shape)

model_data["Churn"].value_counts(
    normalize=True
)

(288643, 28)

Churn
0.0    0.787963
1.0    0.212037
Name: proportion, dtype: float64

In [31]:
master = master.sort_values(
    ["Loyalty Number", "Date"]
).reset_index(drop=True)

In [32]:
master["Enrollment_Date"] = pd.to_datetime(
    master["Enrollment Year"].astype(str)
    + "-"
    + master["Enrollment Month"].astype(str)
    + "-01"
)

master["Enrollment_Age_Months"] = (
    (master["Date"] - master["Enrollment_Date"])
    .dt.days
    / 30
).astype(int)

In [33]:
grouped = master.groupby("Loyalty Number")

In [34]:
master["Flights_3M"] = (
    grouped["Total Flights"]
    .transform(
        lambda x: x.shift(1)
        .rolling(3, min_periods=1)
        .sum()
    )
)

In [35]:
master["Distance_3M"] = (
    grouped["Distance"]
    .transform(
        lambda x: x.shift(1)
        .rolling(3, min_periods=1)
        .sum()
    )
)

In [36]:
master["Points_3M"] = (
    grouped["Points Accumulated"]
    .transform(
        lambda x: x.shift(1)
        .rolling(3, min_periods=1)
        .sum()
    )
)

In [37]:
master["Redeemed_3M"] = (
    grouped["Points Redeemed"]
    .transform(
        lambda x: x.shift(1)
        .rolling(3, min_periods=1)
        .sum()
    )
)

In [38]:
master["Flights_6M"] = (
    grouped["Total Flights"]
    .transform(
        lambda x: x.shift(1)
        .rolling(6, min_periods=1)
        .sum()
    )
)

In [39]:
master["Distance_6M"] = (
    grouped["Distance"]
    .transform(
        lambda x: x.shift(1)
        .rolling(6, min_periods=1)
        .sum()
    )
)

In [40]:
master["Points_6M"] = (
    grouped["Points Accumulated"]
    .transform(
        lambda x: x.shift(1)
        .rolling(6, min_periods=1)
        .sum()
    )
)

In [41]:
master["Redeemed_6M"] = (
    grouped["Points Redeemed"]
    .transform(
        lambda x: x.shift(1)
        .rolling(6, min_periods=1)
        .sum()
    )
)

In [42]:
master["Flight_Trend"] = (
    master["Flights_3M"]
    - (
        grouped["Total Flights"]
        .transform(
            lambda x: x.shift(4)
            .rolling(3, min_periods=1)
            .sum()
        )
    )
)

In [43]:
master["Active"] = (
    master["Total Flights"] > 0
).astype(int)

In [44]:
master["Last_Active_Date"] = (
    master["Date"]
    .where(master["Active"] == 1)
)

In [45]:
master["Last_Active_Date"] = (
    master.groupby("Loyalty Number")
    ["Last_Active_Date"]
    .ffill()
)

In [46]:
master["Months_Since_Last_Active"] = (
    (
        master["Date"]
        - master["Last_Active_Date"]
    ).dt.days
    / 30
).fillna(999)

In [47]:
master["Redeem_Ratio"] = (
    master["Redeemed_6M"]
    /
    (master["Points_6M"] + 1)
)

In [48]:
feature_cols = [
    "Enrollment_Age_Months",
    "Flights_3M",
    "Flights_6M",
    "Distance_3M",
    "Distance_6M",
    "Points_3M",
    "Points_6M",
    "Redeemed_3M",
    "Redeemed_6M",
    "Flight_Trend",
    "Months_Since_Last_Active",
    "Redeem_Ratio"
]

master[feature_cols].describe()

,Enrollment_Age_Months,Flights_3M,Flights_6M,Distance_3M,Distance_6M,Points_3M,Points_6M,Redeemed_3M,Redeemed_6M,Flight_Trend,Months_Since_Last_Active,Redeem_Ratio
count,389065.000000,372328.000000,372328.000000,372328.000000,372328.000000,372328.000000,372328.000000,372328.000000,372328.000000,322117.000000,389065.000000,372328.000000
mean,27.962783,3.705902,6.792138,5555.940509,10180.791490,5783.421025,10556.411441,89.794044,165.657254,0.442805,236.427789,0.838260
std,24.230726,4.111698,6.609677,6572.452519,10365.100791,8015.436140,12506.291210,220.566521,310.631682,4.790465,423.768943,20.178144
min,-23.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-68.000000,0.000000,0.000000
25%,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-2.000000,0.000000,0.000000
50%,27.000000,3.000000,6.000000,4106.000000,8840.000000,4122.000000,8876.000000,0.000000,0.000000,0.000000,1.000000,0.000000
75%,48.000000,6.000000,11.000000,8707.250000,15888.000000,8748.000000,15927.000000,0.000000,349.000000,3.000000,9.100000,0.017275
max,81.000000,72.000000,94.000000,140264.000000,169252.000000,210396.000000,253878.000000,2234.000000,3030.000000,68.000000,999.000000,1175.000000

In [49]:
master = master[
    master["Date"] >= master["Enrollment_Date"]
].copy()

print(master.shape)

(336191, 43)

In [50]:
master["Never_Active"] = (
    master["Last_Active_Date"]
    .isna()
).astype(int)

In [51]:
master["Months_Since_Last_Active"] = (
    (
        master["Date"]
        - master["Last_Active_Date"]
    ).dt.days / 30
)

master["Months_Since_Last_Active"] = (
    master["Months_Since_Last_Active"]
    .fillna(24)
)

In [52]:
master["Redeem_Ratio"] = np.where(
    master["Points_6M"] > 0,
    master["Redeemed_6M"] / master["Points_6M"],
    0
)

In [53]:
master["Frequency_Score"] = (
    master["Flights_6M"]
)

In [54]:
master["Monetary_Score"] = (
    master["Points_6M"]
)

In [55]:
master["Customer_Tenure_Group"] = pd.cut(
    master["Enrollment_Age_Months"],
    bins=[0,12,24,48,120],
    labels=[
        "New",
        "Developing",
        "Established",
        "Veteran"
    ]
)

In [56]:
master.shape

master[
[
"Enrollment_Age_Months",
"Months_Since_Last_Active",
"Redeem_Ratio"
]
].describe()

       Enrollment_Age_Months  Months_Since_Last_Active   Redeem_Ratio
count          336191.000000             336191.000000  336191.000000
mean               33.684227                  3.962589       0.017447
std                20.814220                  8.036381       0.046263
min                 0.000000                  0.000000       0.000000
25%                16.000000                  0.000000       0.000000
50%                33.000000                  0.000000       0.000000
75%                51.000000                  2.033333       0.021665
max                81.000000                 24.000000       2.328696

In [57]:
model_data = master[
    master["Churn"].notna()
].copy()

print(model_data.shape)

(239170, 47)

In [58]:
feature_cols = [
    "Enrollment_Age_Months",
    "Flights_3M",
    "Flights_6M",
    "Distance_3M",
    "Distance_6M",
    "Points_3M",
    "Points_6M",
    "Redeemed_3M",
    "Redeemed_6M",
    "Flight_Trend",
    "Months_Since_Last_Active",
    "Redeem_Ratio",
    "CLV"
]

In [59]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

model_data["Loyalty_Card_Encoded"] = (
    le.fit_transform(
        model_data["Loyalty Card"]
    )
)

feature_cols.append(
    "Loyalty_Card_Encoded"
)

In [60]:
feature_cols.append("Never_Active")

In [61]:
train = model_data[
    model_data["Date"] < "2018-07-01"
]

test = model_data[
    model_data["Date"] >= "2018-07-01"
]

print(train.shape)
print(test.shape)

(239170, 48)
(0, 48)

In [62]:
X_train = train[feature_cols]
X_test = test[feature_cols]

y_train = train["Churn"]
y_test = test["Churn"]

In [63]:
X_train = X_train.fillna(0)
X_test = X_test.fillna(0)

In [64]:
print(model_data["Date"].min())
print(model_data["Date"].max())

2017-01-01 00:00:00
2018-06-01 00:00:00

In [65]:
train = model_data[
    model_data["Date"] < "2018-01-01"
]

In [66]:
test = model_data[
    model_data["Date"] >= "2018-01-01"
]

In [67]:
print(train.shape)
print(test.shape)

print(train["Date"].min(), train["Date"].max())
print(test["Date"].min(), test["Date"].max())

(151063, 48)
(88107, 48)
2017-01-01 00:00:00 2017-12-01 00:00:00
2018-01-01 00:00:00 2018-06-01 00:00:00

In [68]:
print(X_train.shape)
print(X_test.shape)

(239170, 15)
(0, 15)

In [69]:
model_data[feature_cols].isnull().sum().sort_values(ascending=False)

Flight_Trend                49832
Flights_6M                  11723
Flights_3M                  11723
Points_3M                   11723
Distance_6M                 11723
Points_6M                   11723
Distance_3M                 11723
Redeemed_6M                 11723
Redeemed_3M                 11723
Enrollment_Age_Months           0
Months_Since_Last_Active        0
Redeem_Ratio                    0
CLV                             0
Loyalty_Card_Encoded            0
Never_Active                    0
dtype: int64

In [70]:
print(model_data["Date"].min())
print(model_data["Date"].max())

train = model_data[
    model_data["Date"] < "2018-01-01"
]

test = model_data[
    model_data["Date"] >= "2018-01-01"
]

print(train.shape)
print(test.shape)

2017-01-01 00:00:00
2018-06-01 00:00:00
(151063, 48)
(88107, 48)

In [71]:
print(model_data.shape)

print(model_data["Date"].min())
print(model_data["Date"].max())

(239170, 48)
2017-01-01 00:00:00
2018-06-01 00:00:00

In [72]:
print(model_data.groupby(model_data["Date"].dt.year).size())

Date
2017    151063
2018     88107
dtype: int64

In [73]:
model_data[
    model_data["Date"] >= "2018-01-01"
].shape

(88107, 48)

In [74]:
X_train = train[feature_cols].copy()
X_test = test[feature_cols].copy()

X_train = X_train.fillna(0)
X_test = X_test.fillna(0)

In [75]:
master["Flight_Trend"] = (
    master["Flight_Trend"]
    .fillna(0)
)

In [76]:
rolling_features = [
    "Flights_3M",
    "Flights_6M",
    "Distance_3M",
    "Distance_6M",
    "Points_3M",
    "Points_6M",
    "Redeemed_3M",
    "Redeemed_6M",
    "Flight_Trend"
]

master[rolling_features] = (
    master[rolling_features]
    .fillna(0)
)

In [77]:
print(train.shape)
print(test.shape)

X_train = train[feature_cols].copy()
X_test = test[feature_cols].copy()

print(X_train.shape)
print(X_test.shape)

(151063, 48)
(88107, 48)
(151063, 15)
(88107, 15)

In [78]:
rolling_features = [
    "Flights_3M",
    "Flights_6M",
    "Distance_3M",
    "Distance_6M",
    "Points_3M",
    "Points_6M",
    "Redeemed_3M",
    "Redeemed_6M",
    "Flight_Trend"
]

master[rolling_features] = (
    master[rolling_features]
    .fillna(0)
)

In [79]:
model_data = master[
    master["Churn"].notna()
].copy()

In [80]:
train
test
X_train
X_test

,Enrollment_Age_Months,Flights_3M,Flights_6M,Distance_3M,Distance_6M,Points_3M,Points_6M,Redeemed_3M,Redeemed_6M,Flight_Trend,Months_Since_Last_Active,Redeem_Ratio,CLV,Loyalty_Card_Encoded,Never_Active
12,17,8.0,17.0,6814.0,23368.0,6814.0,23368.0,0.0,690.0,-1.0,1.033333,0.029528,7919.20,0,0
13,18,6.0,14.0,3086.0,19681.0,3086.0,19681.0,0.0,690.0,-2.0,0.000000,0.035059,7919.20,0,0
14,19,4.0,13.0,5966.0,17473.0,5966.0,17473.0,0.0,0.0,-5.0,0.000000,0.000000,7919.20,0,0
15,20,4.0,12.0,6322.0,13136.0,6322.0,13136.0,0.0,0.0,-4.0,0.000000,0.000000,7919.20,0,0
16,21,5.0,11.0,7053.0,10139.0,7053.0,10139.0,0.0,0.0,-1.0,1.000000,0.000000,7919.20,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389054,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,8257.01,1,0
389055,0,1.0,1.0,1786.0,1786.0,2679.0,2679.0,544.0,544.0,NaN,0.000000,0.203061,8257.01,1,0
389056,1,2.0,2.0,2855.0,2855.0,4282.5,4282.5,544.0,544.0,NaN,1.033333,0.127029,8257.01,1,0
389057,2,2.0,2.0,2855.0,2855.0,4282.5,4282.5,544.0,544.0,NaN,2.033333,0.127029,8257.01,1,0
389058,4,1.0,2.0,1069.0,2855.0,1603.5,4282.5,0.0,544.0,0.0,3.066667,0.127029,8257.01,1,0

In [81]:
rolling_features = [
    "Flights_3M",
    "Flights_6M",
    "Distance_3M",
    "Distance_6M",
    "Points_3M",
    "Points_6M",
    "Redeemed_3M",
    "Redeemed_6M",
    "Flight_Trend"
]

master[rolling_features] = (
    master[rolling_features]
    .fillna(0)
)

In [82]:
model_data = master[
    master["Churn"].notna()
].copy()

In [83]:
train = model_data[
    model_data["Date"] < "2018-01-01"
]

test = model_data[
    model_data["Date"] >= "2018-01-01"
]

In [84]:
print("Loyalty_Card_Encoded" in model_data.columns)

False

In [85]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

model_data["Loyalty_Card_Encoded"] = (
    le.fit_transform(
        model_data["Loyalty Card"]
    )
)

In [86]:
print(model_data["Loyalty_Card_Encoded"].head())

0    0
1    0
2    0
3    0
4    0
Name: Loyalty_Card_Encoded, dtype: int64

In [87]:
train = model_data[
    model_data["Date"] < "2018-01-01"
].copy()

test = model_data[
    model_data["Date"] >= "2018-01-01"
].copy()

In [88]:
model_data[feature_cols].isnull().sum().sort_values(
    ascending=False
)

Enrollment_Age_Months       0
Flights_3M                  0
Flights_6M                  0
Distance_3M                 0
Distance_6M                 0
Points_3M                   0
Points_6M                   0
Redeemed_3M                 0
Redeemed_6M                 0
Flight_Trend                0
Months_Since_Last_Active    0
Redeem_Ratio                0
CLV                         0
Loyalty_Card_Encoded        0
Never_Active                0
dtype: int64

In [89]:
model_data[feature_cols].isnull().sum()

Enrollment_Age_Months       0
Flights_3M                  0
Flights_6M                  0
Distance_3M                 0
Distance_6M                 0
Points_3M                   0
Points_6M                   0
Redeemed_3M                 0
Redeemed_6M                 0
Flight_Trend                0
Months_Since_Last_Active    0
Redeem_Ratio                0
CLV                         0
Loyalty_Card_Encoded        0
Never_Active                0
dtype: int64

In [90]:
print(train.shape)
print(test.shape)

print(
    model_data[feature_cols]
    .isnull()
    .sum()
    .sum()
)

(151063, 48)
(88107, 48)
0

In [91]:
X_train = train[feature_cols].copy()
X_test = test[feature_cols].copy()

y_train = train["Churn"]
y_test = test["Churn"]

In [92]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [93]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    random_state=42
)

lr.fit(
    X_train_scaled,
    y_train
)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [94]:
y_pred = lr.predict(X_test_scaled)

y_prob = lr.predict_proba(
    X_test_scaled
)[:,1]

In [95]:
from sklearn.metrics import (
    classification_report,
    roc_auc_score,
    confusion_matrix
)

print(classification_report(
    y_test,
    y_pred
))

print(
    "ROC AUC:",
    roc_auc_score(
        y_test,
        y_prob
    )
)

print(
    confusion_matrix(
        y_test,
        y_pred
    )
)

              precision    recall  f1-score   support

         0.0       0.98      0.94      0.96     76207
         1.0       0.69      0.89      0.78     11900

    accuracy                           0.93     88107
   macro avg       0.84      0.91      0.87     88107
weighted avg       0.94      0.93      0.94     88107

ROC AUC: 0.9530121182542066
[[71546  4661]
 [ 1347 10553]]

In [96]:
coef_df = pd.DataFrame({
    "Feature": feature_cols,
    "Coefficient": lr.coef_[0]
})

coef_df["Abs_Coefficient"] = (
    coef_df["Coefficient"]
    .abs()
)

coef_df.sort_values(
    "Abs_Coefficient",
    ascending=False
).head(15)

                     Feature  Coefficient  Abs_Coefficient
10  Months_Since_Last_Active     7.165179         7.165179
14              Never_Active    -5.488545         5.488545
1                 Flights_3M    -0.139726         0.139726
0      Enrollment_Age_Months     0.087127         0.087127
8                Redeemed_6M     0.064336         0.064336
7                Redeemed_3M    -0.051459         0.051459
9               Flight_Trend     0.044137         0.044137
13      Loyalty_Card_Encoded    -0.043336         0.043336
2                 Flights_6M     0.041201         0.041201
6                  Points_6M     0.032981         0.032981
4                Distance_6M     0.032981         0.032981
11              Redeem_Ratio    -0.020870         0.020870
12                       CLV     0.017635         0.017635
5                  Points_3M     0.016978         0.016978
3                Distance_3M     0.016978         0.016978

In [97]:
pd.crosstab(
    pd.cut(
        model_data["Months_Since_Last_Active"],
        bins=[0,1,3,6,12,24]
    ),
    model_data["Churn"],
    normalize="index"
)

Churn                          0.0       1.0
Months_Since_Last_Active
(0, 1]                    0.977728  0.022272
(1, 3]                    0.967410  0.032590
(3, 6]                    0.810740  0.189260
(6, 12]                   0.155144  0.844856
(12, 24]                  0.360657  0.639343

In [98]:
model_data_v2 = model_data[
    model_data["Months_Since_Last_Active"] <= 3
].copy()

In [99]:
model_data_v2.shape

model_data_v2["Churn"].value_counts(normalize=True)

Churn
0.0    0.982935
1.0    0.017065
Name: proportion, dtype: float64

In [100]:
!pip install xgboost -q

In [101]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="logloss"
)

xgb.fit(
    X_train,
    y_train
)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, ...)

In [102]:
from sklearn.metrics import (
    roc_auc_score,
    classification_report
)

y_prob_xgb = xgb.predict_proba(X_test)[:,1]

y_pred_xgb = (
    y_prob_xgb > 0.5
).astype(int)

print(
    classification_report(
        y_test,
        y_pred_xgb
    )
)

print(
    "ROC-AUC:",
    roc_auc_score(
        y_test,
        y_prob_xgb
    )
)

              precision    recall  f1-score   support

         0.0       0.97      0.99      0.98     76207
         1.0       0.96      0.83      0.89     11900

    accuracy                           0.97     88107
   macro avg       0.97      0.91      0.94     88107
weighted avg       0.97      0.97      0.97     88107

ROC-AUC: 0.966801095049276

In [103]:
importance_df = pd.DataFrame({
    "Feature": feature_cols,
    "Importance": xgb.feature_importances_
})

importance_df = (
    importance_df
    .sort_values(
        "Importance",
        ascending=False
    )
)

importance_df.head(15)

                     Feature  Importance
14              Never_Active    0.625385
10  Months_Since_Last_Active    0.296715
0      Enrollment_Age_Months    0.028267
1                 Flights_3M    0.015210
7                Redeemed_3M    0.005454
2                 Flights_6M    0.004070
12                       CLV    0.003461
4                Distance_6M    0.003187
6                  Points_6M    0.003101
8                Redeemed_6M    0.002904
13      Loyalty_Card_Encoded    0.002762
3                Distance_3M    0.002615
11              Redeem_Ratio    0.002601
5                  Points_3M    0.002367
9               Flight_Trend    0.001901

In [104]:
customer_seg = (
    master
    .groupby("Loyalty Number")
    .agg({
        "Total Flights":"sum",
        "Distance":"sum",
        "Points Accumulated":"sum",
        "Points Redeemed":"sum",
        "CLV":"first",
        "Enrollment_Age_Months":"max",
        "Months_Since_Last_Active":"last"
    })
    .reset_index()
)

In [105]:
customer_seg["Avg_Distance_Per_Flight"] = (
    customer_seg["Distance"]
    /
    (customer_seg["Total Flights"] + 1)
)

customer_seg["Redeem_Ratio"] = (
    customer_seg["Points Redeemed"]
    /
    (customer_seg["Points Accumulated"] + 1)
)

In [106]:
from sklearn.preprocessing import StandardScaler

seg_features = [
    "Total Flights",
    "Distance",
    "Points Accumulated",
    "Points Redeemed",
    "CLV",
    "Enrollment_Age_Months",
    "Months_Since_Last_Active",
    "Redeem_Ratio"
]

scaler = StandardScaler()

X_seg = scaler.fit_transform(
    customer_seg[seg_features]
)

In [107]:
from sklearn.cluster import KMeans

inertia = []

for k in range(2,11):

    km = KMeans(
        n_clusters=k,
        random_state=42
    )

    km.fit(X_seg)

    inertia.append(km.inertia_)

In [108]:
kmeans = KMeans(
    n_clusters=5,
    random_state=42
)

customer_seg["Segment"] = (
    kmeans.fit_predict(X_seg)
)

In [109]:
customer_seg["Segment"].value_counts().sort_index()

Segment
0    2457
1    3814
2    2007
3    8450
4       9
Name: count, dtype: int64

In [110]:
segment_profile = customer_seg.groupby(
    "Segment"
)[seg_features].mean().round(2)

segment_profile

,Total Flights,Distance,Points Accumulated,Points Redeemed,CLV,Enrollment_Age_Months,Months_Since_Last_Active,Redeem_Ratio
Segment,,,,,,,,
0,49.64,76695.24,88579.84,767.95,13393.77,32.92,0.50,0.01
1,15.93,23296.25,24135.33,333.54,7881.77,12.72,1.52,0.02
2,1.94,2902.43,2902.43,51.47,8269.99,41.15,22.77,0.00
3,37.15,55305.10,55415.00,1041.39,6399.95,51.05,0.82,0.02
4,0.00,0.00,0.00,469.89,7020.38,11.56,24.00,469.89

In [111]:
(
    customer_seg["Segment"]
    .value_counts(normalize=True)
    .sort_index()
    * 100
).round(2)

Segment
0    14.68
1    22.79
2    11.99
3    50.49
4     0.05
Name: proportion, dtype: float64

In [112]:
customer_seg.groupby(
    "Segment"
)["CLV"].agg(
    ["count","mean","median","max"]
).round(2)

         count      mean   median       max
Segment
0         2457  13393.77  9268.67  83325.38
1         3814   7881.77  5791.09  60556.19
2         2007   8269.99  5846.11  83325.38
3         8450   6399.95  5354.27  33473.35
4            9   7020.38  3096.51  31221.75

In [113]:
segment_map = customer_seg[
    ["Loyalty Number","Segment"]
]

model_with_segment = model_data.merge(
    segment_map,
    on="Loyalty Number",
    how="left"
)

In [114]:
model_with_segment.groupby(
    "Segment"
)["Churn"].mean().round(4)

Segment
0    0.0011
1    0.0665
2    0.9336
3    0.0071
4    1.0000
Name: Churn, dtype: float64

In [115]:
customer_seg = customer_seg[
    customer_seg["Segment"] != 4
].copy()

In [116]:
customer_risk = model_data.copy()

customer_risk["Risk_Probability"] = (
    xgb.predict_proba(
        model_data[feature_cols]
    )[:,1]
)

In [117]:
customer_risk["Risk_Level"] = pd.cut(
    customer_risk["Risk_Probability"],
    bins=[0,0.25,0.50,0.75,1.0],
    labels=[
        "Low",
        "Medium",
        "High",
        "Critical"
    ]
)

In [118]:
customer_risk["Risk_Level"].value_counts()

Risk_Level
Low         204616
High         21456
Critical      9893
Medium        3205
Name: count, dtype: int64

In [119]:
segment_map = customer_seg[
    ["Loyalty Number","Segment"]
]

customer_risk = customer_risk.merge(
    segment_map,
    on="Loyalty Number",
    how="left"
)

In [120]:
segment_names = {
    0:"Champions",
    1:"Loyal Regulars",
    2:"Dormant Members",
    3:"Established Loyalists"
}

customer_risk["Segment_Name"] = (
    customer_risk["Segment"]
    .map(segment_names)
)

In [121]:
def retention_action(row):

    segment = row["Segment_Name"]
    risk = row["Risk_Level"]

    if segment == "Champions" and risk in ["High","Critical"]:
        return "VIP Outreach + Tier Benefits"

    elif segment == "Loyal Regulars" and risk in ["High","Critical"]:
        return "Bonus Points Campaign"

    elif segment == "Dormant Members":
        return "Win-Back Offer"

    elif segment == "Established Loyalists" and risk in ["Medium","High"]:
        return "Anniversary Reward"

    else:
        return "No Immediate Action"

In [122]:
customer_risk["Recommended_Action"] = (
    customer_risk.apply(
        retention_action,
        axis=1
    )
)

In [123]:
dashboard_data = customer_risk[
[
    "Loyalty Number",
    "CLV",
    "Risk_Probability",
    "Risk_Level",
    "Segment_Name",
    "Recommended_Action",
    "Months_Since_Last_Active",
    "Flights_6M",
    "Points_6M"
]
]

In [124]:
dashboard_data.to_csv(
    "dashboard_data.csv",
    index=False
)

In [125]:
dashboard_data["Risk_Level"].value_counts()

Risk_Level
Low         204616
High         21456
Critical      9893
Medium        3205
Name: count, dtype: int64

In [126]:
dashboard_data.groupby(
    "Segment_Name"
)["CLV"].mean()

Segment_Name
Champions                14703.839911
Dormant Members           8410.011294
Established Loyalists     6417.202256
Loyal Regulars            7808.455634
Name: CLV, dtype: float64

In [127]:
dashboard_data.groupby(
    "Segment_Name"
)["Risk_Probability"].mean()

Segment_Name
Champions                0.030908
Dormant Members          0.663594
Established Loyalists    0.041656
Loyal Regulars           0.063946
Name: Risk_Probability, dtype: float32

In [128]:
customer_risk["Revenue_At_Risk"] = (
    customer_risk["CLV"]
    *
    customer_risk["Risk_Probability"]
)

In [129]:
customer_risk["Revenue_At_Risk"].sum()

np.float64(237621267.00013754)

In [130]:
customer_risk.groupby(
    "Segment_Name"
)["Revenue_At_Risk"].sum().sort_values(
    ascending=False
)

Segment_Name
Dormant Members          1.670082e+08
Established Loyalists    4.077821e+07
Champions                1.680823e+07
Loyal Regulars           1.286597e+07
Name: Revenue_At_Risk, dtype: float64

In [131]:
retention_matrix = (
    customer_risk.groupby(
        ["Segment_Name","Risk_Level"]
    )
    .agg({
        "Loyalty Number":"count",
        "CLV":"mean",
        "Revenue_At_Risk":"sum"
    })
)

/tmp/ipykernel_25850/3511451991.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  customer_risk.groupby(

In [132]:
customer_risk["Revenue_At_Risk"] = (
    customer_risk["CLV"]
    * customer_risk["Risk_Probability"]
)

customer_risk["Revenue_At_Risk"].sum()

np.float64(237621267.00013754)

In [133]:
customer_risk.groupby(
    "Segment_Name"
)["Revenue_At_Risk"].sum().sort_values(
    ascending=False
)

Segment_Name
Dormant Members          1.670082e+08
Established Loyalists    4.077821e+07
Champions                1.680823e+07
Loyal Regulars           1.286597e+07
Name: Revenue_At_Risk, dtype: float64

In [134]:
customer_risk.groupby(
    "Risk_Level"
)["Revenue_At_Risk"].sum().round(0)

/tmp/ipykernel_25850/867833164.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  customer_risk.groupby(

Risk_Level
Low          29678104.0
Medium        8833002.0
High        111681784.0
Critical     87428376.0
Name: Revenue_At_Risk, dtype: float64

In [136]:
pd.pivot_table(
    customer_risk,
    values="Revenue_At_Risk",
    index="Segment_Name",
    columns="Risk_Level",
    aggfunc="sum"
).round(0)

/tmp/ipykernel_25850/1991598957.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pd.pivot_table(

Risk_Level                    Low     Medium        High    Critical
Segment_Name
Champions               7431794.0  1172196.0   6359708.0   1844533.0
Dormant Members         1495572.0  2615153.0  81524502.0  81372933.0
Established Loyalists  15035205.0  2767169.0  20555634.0   2420206.0
Loyal Regulars          5706772.0  2276364.0   3092126.0   1790705.0

In [137]:
top100 = (
    customer_risk
    .sort_values(
        "Revenue_At_Risk",
        ascending=False
    )
    .head(100)
)

top100[
[
"Loyalty Number",
"Segment_Name",
"Risk_Level",
"CLV",
"Revenue_At_Risk",
"Recommended_Action"
]
]

,Loyalty Number,Segment_Name,Risk_Level,CLV,Revenue_At_Risk,Recommended_Action
147860,652627,Dormant Members,Critical,83325.38,68057.885614,Win-Back Offer
147854,652627,Dormant Members,Critical,83325.38,68056.067846,Win-Back Offer
147852,652627,Dormant Members,Critical,83325.38,68056.067846,Win-Back Offer
147853,652627,Dormant Members,Critical,83325.38,68056.067846,Win-Back Offer
147855,652627,Dormant Members,Critical,83325.38,68056.067846,Win-Back Offer
147851,652627,Dormant Members,Critical,83325.38,68038.992745,Win-Back Offer
147857,652627,Dormant Members,Critical,83325.38,67964.757279,Win-Back Offer
147856,652627,Dormant Members,Critical,83325.38,67964.757279,Win-Back Offer
197678,838263,Dormant Members,Critical,67907.27,67652.777860,Win-Back Offer
197684,838263,Dormant Members,Critical,67907.27,67652.777860,Win-Back Offer
197676,838263,Dormant Members,Critical,67907.27,67652.777860,Win-Back Offer
197683,838263,Dormant Members,Critical,67907.27,67652.777860,Win-Back Offer
197682,838263,Dormant Members,Critical,67907.27,67652.777860,Win-Back Offer
197681,838263,Dormant Members,Critical,67907.27,67652.777860,Win-Back Offer
197680,838263,Dormant Members,Critical,67907.27,67652.777860,Win-Back Offer
197679,838263,Dormant Members,Critical,67907.27,67652.777860,Win-Back Offer
197677,838263,Dormant Members,Critical,67907.27,67652.777860,Win-Back Offer
197675,838263,Dormant Members,Critical,67907.27,67645.844341,Win-Back Offer
197674,838263,Dormant Members,Critical,67907.27,67577.832708,Win-Back Offer
147859,652627,Dormant Members,Critical,83325.38,67525.363975,Win-Back Offer
147858,652627,Dormant Members,Critical,83325.38,67473.711546,Win-Back Offer
197673,838263,Dormant Members,Critical,67907.27,67472.057072,Win-Back Offer
197672,838263,Dormant Members,Critical,67907.27,67299.896934,Win-Back Offer
147850,652627,Dormant Members,Critical,83325.38,67224.558110,Win-Back Offer
147849,652627,Dormant Members,Critical,83325.38,66850.167401,Win-Back Offer
197671,838263,Dormant Members,Critical,67907.27,66411.426927,Win-Back Offer
147848,652627,Dormant Members,Critical,83325.38,64877.332689,Win-Back Offer
147847,652627,Dormant Members,Critical,83325.38,64439.230696,Win-Back Offer
197670,838263,Dormant Members,Critical,67907.27,64170.086824,Win-Back Offer
147846,652627,Dormant Members,Critical,83325.38,63604.934709,Win-Back Offer
179503,767366,Dormant Members,Critical,73225.96,63307.656074,Win-Back Offer
147845,652627,Dormant Members,High,83325.38,61585.101254,Win-Back Offer
179502,767366,Dormant Members,Critical,73225.96,60274.096851,Win-Back Offer
147844,652627,Dormant Members,High,83325.38,60187.073640,Win-Back Offer
199282,844145,Dormant Members,Critical,74228.52,59181.472902,Win-Back Offer
199283,844145,Dormant Members,Critical,74228.52,59181.472902,Win-Back Offer
199284,844145,Dormant Members,Critical,74228.52,59181.472902,Win-Back Offer
199275,844145,Dormant Members,Critical,74228.52,59179.729703,Win-Back Offer
199274,844145,Dormant Members,Critical,74228.52,59179.729703,Win-Back Offer
199276,844145,Dormant Members,Critical,74228.52,59179.729703,Win-Back Offer
199277,844145,Dormant Members,Critical,74228.52,59179.729703,Win-Back Offer
199273,844145,Dormant Members,Critical,74228.52,59142.945536,Win-Back Offer
199285,844145,Dormant Members,Critical,74228.52,59104.825210,Win-Back Offer
199279,844145,Dormant Members,Critical,74228.52,59091.892793,Win-Back Offer
199278,844145,Dormant Members,Critical,74228.52,59091.892793,Win-Back Offer
197669,838263,Dormant Members,Critical,67907.27,58960.459686,Win-Back Offer
199281,844145,Dormant Members,Critical,74228.52,58669.587195,Win-Back Offer
199280,844145,Dormant Members,Critical,74228.52,58619.985644,Win-Back Offer
197668,838263,Dormant Members,Critical,67907.27,58603.102127,Win-Back Offer
199272,844145,Dormant Members,Critical,74228.52,58359.682579,Win-Back Offer
199271,844145,Dormant Members,Critical,74228.52,58000.309142,Win-Back Offer
197667,838263,Dormant Members,Critical,67907.27,57582.676681,Win-Back Offer
199270,844145,Dormant Members,Critical,74228.52,55989.846913,Win-Back Offer
147843,652627,Dormant Members,High,83325.38,55922.932228,Win-Back Offer
199269,844145,Dormant Members,High,74228.52,55570.554307,Win-Back Offer
131249,592992,Champions,Critical,61850.19,55443.762189,VIP Outreach + Tier Benefits
199268,844145,Dormant Members,High,74228.52,54773.788190,Win-Back Offer
131248,592992,Champions,Critical,61850.19,53504.864616,VIP Outreach + Tier Benefits
179501,767366,Dormant Members,High,73225.96,53013.249570,Win-Back Offer
105215,495253,Champions,Critical,66025.75,52639.956157,VIP Outreach + Tier Benefits
105214,495253,Champions,Critical,66025.75,52607.236898,VIP Outreach + Tier Benefits
113932,529331,Dormant Members,Critical,49221.43,48982.642980,Win-Back Offer
113931,529331,Dormant Members,Critical,49221.43,48905.973309,Win-Back Offer
113930,529331,Dormant Members,Critical,49221.43,48781.185961,Win-Back Offer
170787,737027,Dormant Members,Critical,49221.43,48767.382310,Win-Back Offer
170788,737027,Dormant Members,Critical,49221.43,48767.382310,Win-Back Offer
170784,737027,Dormant Members,Critical,49221.43,48767.382310,Win-Back Offer
170783,737027,Dormant Members,Critical,49221.43,48767.382310,Win-Back Offer
170786,737027,Dormant Members,Critical,49221.43,48767.382310,Win-Back Offer
170785,737027,Dormant Members,Critical,49221.43,48767.382310,Win-Back Offer
170782,737027,Dormant Members,Critical,49221.43,48767.382310,Win-Back Offer
170789,737027,Dormant Members,Critical,49221.43,48767.382310,Win-Back Offer
170781,737027,Dormant Members,Critical,49221.43,48767.382310,Win-Back Offer
170780,737027,Dormant Members,Critical,49221.43,48767.382310,Win-Back Offer
170779,737027,Dormant Members,Critical,49221.43,48767.382310,Win-Back Offer
170778,737027,Dormant Members,Critical,49221.43,48767.382310,Win-Back Offer
170777,737027,Dormant Members,Critical,49221.43,48755.080778,Win-Back Offer
170776,737027,Dormant Members,Critical,49221.43,48634.614955,Win-Back Offer
170775,737027,Dormant Members,Critical,49221.43,48503.431866,Win-Back Offer
170774,737027,Dormant Members,Critical,49221.43,48222.658864,Win-Back Offer
113929,529331,Dormant Members,Critical,49221.43,48137.193583,Win-Back Offer
136689,612144,Champions,High,64618.76,48005.828479,VIP Outreach + Tier Benefits
153201,672917,Dormant Members,Critical,58166.55,47508.843122,Win-Back Offer
153202,672917,Dormant Members,Critical,58166.55,47508.843122,Win-Back Offer
153200,672917,Dormant Members,Critical,58166.55,47508.843122,Win-Back Offer
153195,672917,Dormant Members,Critical,58166.55,47507.574201,Win-Back Offer
153194,672917,Dormant Members,Critical,58166.55,47507.574201,Win-Back Offer
153203,672917,Dormant Members,Critical,58166.55,47453.218629,Win-Back Offer
153196,672917,Dormant Members,Critical,58166.55,47443.833469,Win-Back Offer
153197,672917,Dormant Members,Critical,58166.55,47443.833469,Win-Back Offer
153205,672917,Dormant Members,Critical,58166.55,47361.922209,Win-Back Offer
153204,672917,Dormant Members,Critical,58166.55,47361.922209,Win-Back Offer
153199,672917,Dormant Members,Critical,58166.55,47137.108285,Win-Back Offer
153198,672917,Dormant Members,Critical,58166.55,47101.051520,Win-Back Offer
170773,737027,Dormant Members,Critical,49221.43,46952.432558,Win-Back Offer
113928,529331,Dormant Members,Critical,49221.43,46512.596320,Win-Back Offer
153206,672917,Dormant Members,Critical,58166.55,46206.237046,Win-Back Offer
53381,302460,Champions,Critical,56675.94,45929.145203,VIP Outreach + Tier Benefits
153207,672917,Dormant Members,Critical,58166.55,45910.037662,Win-Back Offer
53380,302460,Champions,Critical,56675.94,45894.012451,VIP Outreach + Tier Benefits

In [138]:
final_dashboard_df = customer_risk[[
    "Loyalty Number",
    "Segment_Name",
    "Risk_Level",
    "Risk_Probability",
    "CLV",
    "Revenue_At_Risk",
    "Recommended_Action"
]].copy()

final_dashboard_df.to_csv(
    "final_customer_risk_dashboard.csv",
    index=False
)

In [139]:
rev_segment = (
    customer_risk
    .groupby("Segment_Name")["Revenue_At_Risk"]
    .sum()
    .reset_index()
)

In [140]:
rev_risk = (
    customer_risk
    .groupby("Risk_Level")["Revenue_At_Risk"]
    .sum()
    .reset_index()
)

/tmp/ipykernel_25850/4247003404.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby("Risk_Level")["Revenue_At_Risk"]

In [141]:
segment_dist = (
    customer_risk["Segment_Name"]
    .value_counts(normalize=True)
    .mul(100)
    .reset_index()
)

In [142]:
segment_churn = (
    customer_risk
    .groupby("Segment_Name")["Churn"]
    .mean()
    .mul(100)
    .reset_index()
)